### ISSUE TITLE
parse rdb serialized by protocol buffer

### ISSUE THREAD

**Issue by Lmikic** [jwhitbeck/java-rdb-parser#13]
Hi, I try to use this tool to parse rdb whose value is serialized by protocol buffer. But it fail. What should I do to deal with the problem. Code is as below:

```
public static void parseIdMappingRdbFile(String rdbFilePath) {
        File rdbFile = new File(rdbFilePath);
        RdbParser parser = null;
        try {
            parser = new RdbParser(rdbFile);
        } catch (IOException e) {
            logger.error("fail to parse rdb file[{}]", rdbFile);
            System.exit(-1);
        }
        Entry parsedRdbEntry = null;
        while (true) {
            try {
                parsedRdbEntry = parser.readNext();
                if (null == parsedRdbEntry) {
                    break;
                }
            } catch (IOException e) {
                e.printStackTrace();
                continue;
            }
            if (parsedRdbEntry.getType().equals(KEY_VALUE_PAIR)) {
                KeyValuePair kvp = (KeyValuePair)parsedRdbEntry;
                List<byte[]> values = kvp.getValues();
                if (null == values || values.size() == 0) {
                    continue;
                }
                for (byte[] value : values) {
                    try {
                         // ** here the problem happens: cannot parse from value from rdb file **
                         IdMappingProto.IdMapping idMapping = IdMappingProto.IdMapping.parseFrom(value);
                    } catch (InvalidProtocolBufferException e) {
                        logger.error("[{}]:fail to deserialize class of IdMapping", cnt);  
                        continue; 
                    }
                }
            }
        }
}
```

**Comment by jwhitbeck** [comment]
Hi,

I'm not sure what's causing the problem. To make it easier for me to reproduce, could you send me code and an rdb dump to reproduce the complete write / read cycle? For example, we could:
- define a bogus protobuf message with a single field,
- start an empty redis locally,
- use `redis.clients.jedis.Jedis` to code a Java function that writes a single protobuf value to redis
- start the local redis
- run the code from your comment above
- send me the stack trace, java code, protobuf message description, and rdb dump.

Thanks

**Comment by Lmikic** [comment]
Thanks for your reply: 
I put the sample code here:
[https://github.com/Lmikic/rdbparser/tree/master/rdbparser_sample](https://github.com/Lmikic/rdbparser/tree/master/rdbparser_sample)

stack trace is as follwing:
```
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
        at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:106)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:635)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:160)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.sogo.rdbparser.proto.IdMappingProto$IdBrief.parseFrom(IdMappingProto.java:446)
        at com.sogo.rdbparser.RdbFileParserMainApplication.parseIdMappingRdbFile(RdbFileParserMainApplication.java:121)
        at com.sogo.rdbparser.RdbFileParserMainApplication.run(RdbFileParserMainApplication.java:42)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at com.sogo.rdbparser.RdbFileParserMainApplication.main(RdbFileParserMainApplication.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

**Comment by Lmikic** [comment]
> Hi,
> 
> I'm not sure what's causing the problem. To make it easier for me to reproduce, could you send me code and an rdb dump to reproduce the complete write / read cycle? For example, we could:
> 
> * define a bogus protobuf message with a single field,
> * start an empty redis locally,
> * use `redis.clients.jedis.Jedis` to code a Java function that writes a single protobuf value to redis
> * stop the local redis to obtain an rdb dump
> * run the code from your comment above
> * send me the stack trace, java code, protobuf message description, and rdb dump.
> 
> Thanks

Thanks for your reply:
I put the sample code here:
[https://github.com/Lmikic/rdbparser/tree/master/rdbparser_sample](https://github.com/Lmikic/rdbparser/tree/master/rdbparser_sample)
stack trace is as follwing:
```
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
        at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:106)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:635)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:160)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.sogo.rdbparser.proto.IdMappingProto$IdBrief.parseFrom(IdMappingProto.java:446)
        at com.sogo.rdbparser.RdbFileParserMainApplication.parseIdMappingRdbFile(RdbFileParserMainApplication.java:121)
        at com.sogo.rdbparser.RdbFileParserMainApplication.run(RdbFileParserMainApplication.java:42)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at com.sogo.rdbparser.RdbFileParserMainApplication.main(RdbFileParserMainApplication.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

**Comment by jwhitbeck** [comment]
Thanks for putting together the reproduction code. I just reviewed it and I should be able to troubleshoot it from there.

Just to set expectations, I expect to work on this issue in the first half of March. I unfortunately won't have time before then.

**Comment by Lmikic** [comment]
> Thanks for putting together the reproduction code. I just reviewed it and I should be able to troubleshoot it from there.
> 
> Just to set expectations, I expect to work on this issue in the first half of March. I unfortunately won't have time before then.

Thank you very much for your reply and help，I will follow this issue util  the first half of March. I find that: the result of serialized data is different between using java and using python:
1. the result of serialized data by using java:
```
"\xac\xed\x00\x05ur\x00\x02[B\xac\xf3\x17\xf8\x06\bT\xe0\x02\x00\x00xp\x00\x00\x00.\b\x01\x12*test_java_TJRnwsSPnfEZveNhexEfdbcUfIlIRGaB
```
2.  the result of serialized data by using python:
```
"\b\x01\x12/test_java_TJRnwsSPnfEZveNhexEfdbcUfIlIRGaB"
```

**Comment by Lmikic** [comment]
> > Thanks for putting together the reproduction code. I just reviewed it and I should be able to troubleshoot it from there.
> > Just to set expectations, I expect to work on this issue in the first half of March. I unfortunately won't have time before then.
> 
> Thank you very much for your reply and help，I will follow this issue util the first half of March. I find that: the result of serialized data is different between using java and using python:
> 
> 1. the result of serialized data by using java:
> 
> ```
> "\xac\xed\x00\x05ur\x00\x02[B\xac\xf3\x17\xf8\x06\bT\xe0\x02\x00\x00xp\x00\x00\x00.\b\x01\x12*test_java_TJRnwsSPnfEZveNhexEfdbcUfIlIRGaB
> ```
> 
> 1. the result of serialized data by using python:
> 
> ```
> "\b\x01\x12/test_java_TJRnwsSPnfEZveNhexEfdbcUfIlIRGaB"
> ```

Hi, 
    I find that when using Jedis insteading spring-boot-starter-data-redis to operate redis, the java-rdb-parser works. Therefore, the question becomes why "spring-boot-starter-data-redi" cannot work

**Comment by jwhitbeck** [comment]
Hi @Lmikic,

Given your experiments, this seems like an issue with the way the spring library is serializing the binary protobuf representation. Given the presence of `[B` in the binary data before the protobuf contents, I suspect it is writing a Java byte array object, rather than the contents of the byte array.

I'm going to close this issue as it doesn't seem to be a problem with java-rdb-parser at this point.
